# Generated by Django 5.0.7 on 2024-07-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_image_table_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
